CREATE TABLE off_the_tee_table (
    id SERIAL PRIMARY KEY,
    pid INT NOT NULL,
    player_name TEXT NOT NULL,
    year INT NOT NULL,
    total_driving FLOAT,
    ball_striking FLOAT,
    longest_drives FLOAT,
    driving_320_plus FLOAT,
    driving_300_320 FLOAT,
    driving_300_plus FLOAT,
    driving_280_300 FLOAT,
    driving_260_280 FLOAT,
    driving_240_260 FLOAT,
    driving_240_or_less FLOAT,
    percent_yards_tee_shot FLOAT,
    percent_yards_tee_shot_par4 FLOAT,
    percent_yards_tee_shot_par5 FLOAT,
    driving_accuracy FLOAT,
    rough_tendency FLOAT,
    right_rough_tendency FLOAT,
    left_rough_tendency FLOAT,
    rrt_score FLOAT,
    lrt_score FLOAT,
    fairway_bunker_tendency FLOAT,
    miss_fairway_other FLOAT,
    hit_fairway FLOAT,
    dist_fairway_edge FLOAT,
    dist_fairway_center FLOAT,
    left_tendency FLOAT,
    right_tendency FLOAT,
    good_drive FLOAT,
    clubhead_speed FLOAT,
    ball_speed FLOAT,
    smash_factor FLOAT,
    launch_angle FLOAT,
    spin_rate FLOAT,
    distance_apex FLOAT,
    apex_height FLOAT,
    hang_time FLOAT,
    carry_distance FLOAT,
    carry_efficiency FLOAT,
    total_distance_efficiency FLOAT,
    total_driving_efficiency FLOAT
);
