CREATE TABLE putting_stats_table (
    id SERIAL PRIMARY KEY,
    pid INT NOT NULL,
    year INT NOT NULL,
    total_putting FLOAT8,
    bonus_putting FLOAT8,
    putting_avg FLOAT8,
    overall_putting_avg FLOAT8,
    birdie_or_better_conv_percent FLOAT8,
    putts_per_rd FLOAT8,
    putts_per_rd1 FLOAT8,
    putts_per_rd2 FLOAT8,
    putts_per_rd3 FLOAT8,
    putts_per_rd4 FLOAT8,
    one_putts_per_rd FLOAT8,
    two_putts_per_rd FLOAT8,
    three_putts_per_rd FLOAT8,
    three_plus_putts_per_rd FLOAT8,
    one_putt_percent FLOAT8,
    one_putt_percent_rd1 FLOAT8,
    one_putt_percent_rd2 FLOAT8,
    one_putt_percent_rd3 FLOAT8,
    one_putt_percent_rd4 FLOAT8,
    total_one_putts_inside_5ft FLOAT8,
    total_one_putts_5_10 FLOAT8,
    total_one_putts_10_15 FLOAT8,
    total_one_putts_15_20 FLOAT8,
    total_one_putts_20_25 FLOAT8,
    total_one_putts_more_25 FLOAT8,
    longest_putts FLOAT8,
    three_putt_avoidance FLOAT8,
    three_putt_avoidance_rd1 FLOAT8,
    three_putt_avoidance_rd2 FLOAT8,
    three_putt_avoidance_rd3 FLOAT8,
    three_putt_avoidance_rd4 FLOAT8,
    three_putt_avoidance_inside_5ft FLOAT8,
    three_putt_avoidance_inside_5_10 FLOAT8,
    three_putt_avoidance_inside_10_15 FLOAT8,
    three_putt_avoidance_inside_15_20 FLOAT8,
    three_putt_avoidance_inside_20_25 FLOAT8,
    three_putt_avoidance_inside_more_25 FLOAT8,
    total_three_putts_inside_5ft FLOAT8,
    total_three_putts_inside_5_10 FLOAT8,
    total_three_putts_inside_10_15 FLOAT8,
    total_three_putts_inside_15_20 FLOAT8,
    total_three_putts_inside_20_25 FLOAT8,
    total_three_putts_inside_more_25 FLOAT8,
    putts_made_percent_more_25 FLOAT8,
    putts_made_percent_more_20 FLOAT8,
    putts_made_percent_15_25 FLOAT8,
    putts_made_percent_20_25 FLOAT8,
    putts_made_percent_15_20 FLOAT8,
    putts_made_percent_5_15 FLOAT8,
    putts_made_percent_10_15 FLOAT8,
    putts_made_percent_inside_10ft FLOAT8,
    putts_made_percent_5_10 FLOAT8,
    putts_made_percent_3_5 FLOAT8,
    putts_made_percent_inside_5ft FLOAT8,
    putts_made_percent_10ft FLOAT8,
    putts_made_percent_8ft FLOAT8,
    putts_made_percent_7ft FLOAT8,
    putts_made_percent_6ft FLOAT8,
    putts_made_percent_5ft FLOAT8,
    putting_made_percent_more_10 FLOAT8,
    putting_made_percent_4_8 FLOAT8,
    putting_made_percent_4ft FLOAT8,
    putting_from_more_3ft FLOAT8,
    putts_made_per_event_over_10ft FLOAT8,
    putts_made_per_event_over_20ft FLOAT8,
    avg_distance_of_putts_made FLOAT8,
    avg_distance_of_birdie_putts_made FLOAT8,
    avg_distance_of_eagle_putts_made FLOAT8,
    putts_made_distance FLOAT8,
    approach_putt_performance FLOAT8,
    avg_putting_distance_all_1_putts FLOAT8,
    avg_putting_distance_all_2_putts FLOAT8,
    avg_putting_distance_gir_1_putts FLOAT8,
    avg_putting_distance_gir_2_putts FLOAT8,
    gir_putting_avg_more_35 FLOAT8,
    gir_putting_avg_30_35 FLOAT8,
    gir_putting_avg_25_30 FLOAT8,
    gir_putting_more_25 FLOAT8,
    gir_putting_20_25 FLOAT8,
    gir_putting_15_20 FLOAT8,
    gir_putting_10_15 FLOAT8,
    CONSTRAINT putting_stats_pid_year_unique UNIQUE (pid, year) -- Ensures no duplicates
);

ALTER TABLE putting_stats_table 
ADD COLUMN player_name TEXT;


SELECT * FROM putting_stats_table LIMIT 100;


